export {
  createCell,
  createTable,
  insertRow,
  deleteRow,
  insertColumn,
  deleteColumn,
  resizeRow,
  resizeColumn,
  distributeRows,
  distributeColumns,
  mergeCells,
  splitCell,
  getCellAt,
  anchorOf,
  isCovered,
  setCellText,
  getCellText,
  setCellFill,
  tableSize,
  rowY,
  colX,
  cellRect,
  hitTestCell,
  tintHex,
  effectiveCellFill,
} from './tables';
export type { CellAddress, MergeRegion } from './tables';
